var gv_timeZoneData = [
    { offset: -720, value: "International Date Line West", text: "(UTC-12:00) International Date Line West" },
    { offset: -680, value: "Coordinated Universal Time-11", text: "(UTC-11:00) Coordinated Universal Time-11" },
    { offset: -600, value: "Hawaii", text: "(UTC-10:00) Hawaii" },
    { offset: -540, value: "Alaska", text: "(UTC-09:00) Alaska" },
    { offset: -480, value: "Baja California", text: "(UTC-08:00) Baja California" },
    { offset: -480, value: "Pacific Time (US, Canada)", text: "(UTC-08:00) Pacific Time (US and Canada)", selected: "selected"  },
    { offset: -420, value: "Arizona", text: "(UTC-07:00) Arizona" },
    { offset: -420, value: "Chihuahua, La Paz, Mazatlan", text: "(UTC-07:00) Chihuahua, La Paz, Mazatlan" },
    { offset: -420, value: "Mountain Time (US, Canada)", text: "(UTC-07:00) Mountain Time (US and Canada)" },
    { offset: -360, value: "Central America", text: "(UTC-06:00) Central America" },
    { offset: -360, value: "Central Time (US, Canada)", text: "(UTC-06:00) Central Time (US and Canada)" },
    { offset: -360, value: "Guadalajara, Mexico City, Monterrey", text: "(UTC-06:00) Guadalajara, Mexico City, Monterrey" },
    { offset: -360, value: "Saskatchewan", text: "(UTC-06:00) Saskatchewan" },
    { offset: -300, value: "Bogota, Lima, Quito", text: "(UTC-05:00) Bogota, Lima, Quito" },
    { offset: -300, value: "Eastern Time (US, Canada)", text: "(UTC-05:00) Eastern Time (US and Canada)" },
    { offset: -300, value: "Indiana (East)", text: "(UTC-05:00) Indiana (East)" },
    { offset: -270, value: "Caracas", text: "(UTC-04:30) Caracas" },
    { offset: -240, value: "Asuncion", text: "(UTC-04:00) Asuncion" },
    { offset: -240, value: "Atlantic Time (Canada)", text: "(UTC-04:00) Atlantic Time (Canada)" },
    { offset: -240, value: "Cuiaba", text: "(UTC-04:00) Cuiaba" },
    { offset: -240, value: "Georgetown, La Paz, Manaus, San Juan", text: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan" },
    { offset: -240, value: "Santiago", text: "(UTC-04:00) Santiago" },
    { offset: -210, value: "Newfoundland", text: "(UTC-03:30) Newfoundland" },
    { offset: -180, value: "Brasilia", text: "(UTC-03:00) Brasilia" },
    { offset: -180, value: "Buenos Aires", text: "(UTC-03:00) Buenos Aires" },
    { offset: -180, value: "Cayenne, Fortaleza", text: "(UTC-03:00) Cayenne, Fortaleza" },
    { offset: -180, value: "Greenland", text: "(UTC-03:00) Greenland" },
    { offset: -180, value: "Montevideo", text: "(UTC-03:00) Montevideo" },
    { offset: -180, value: "Salvador", text: "(UTC-03:00) Salvador" },
    { offset: -120, value: "Coordinated Universal Time-02", text: "(UTC-02:00) Coordinated Universal Time-02" },
    { offset: -120, value: "Mid-Atlantic", text: "(UTC-02:00) Mid-Atlantic" },
    { offset:  -60, value: "Azores", text: "(UTC-01:00) Azores" },
    { offset:  -60, value: "Cape Verde Is.", text: "(UTC-01:00) Cape Verde Is." },
    { offset:    0, value: "Casablanca", text: "(UTC) Casablanca" },
    { offset:    0, value: "Coordinated Universal Time", text: "(UTC) Coordinated Universal Time" },
    { offset:    0, value: "Dublin, Edinburgh, Lisbon, London", text: "(UTC) Dublin, Edinburgh, Lisbon, London" },
    { offset:    0, value: "Monrovia, Reykjavik", text: "(UTC) Monrovia, Reykjavik" },
    { offset:   60, value: "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", text: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
    { offset:   60, value: "Belgrade, Bratislava, Budapest, Ljubljana, Prague", text: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" },
    { offset:   60, value: "Brussels, Copenhagen, Madrid, Paris", text: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris" },
    { offset:   60, value: "Sarajevo, Skopje, Warsaw, Zagreb", text: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb" },
    { offset:   60, value: "West Central Africa", text: "(UTC+01:00) West Central Africa" },
    { offset:   60, value: "Windhoek", text: "(UTC+01:00) Windhoek" },
    { offset:  120, value: "Amman", text: "(UTC+02:00) Amman" },
    { offset:  120, value: "Athens, Bucharest", text: "(UTC+02:00) Athens, Bucharest" },
    { offset:  120, value: "Beirut", text: "(UTC+02:00) Beirut" },
    { offset:  120, value: "Cairo", text: "(UTC+02:00) Cairo" },
    { offset:  120, value: "Damascus", text: "(UTC+02:00) Damascus" },
    { offset:  120, value: "Harare, Pretoria", text: "(UTC+02:00) Harare, Pretoria" },
    { offset:  120, value: "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", text: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
    { offset:  120, value: "Istanbul", text: "(UTC+02:00) Istanbul" },
    { offset:  120, value: "Jerusalem", text: "(UTC+02:00) Jerusalem" },
    { offset:  120, value: "Nicosia", text: "(UTC+02:00) Nicosia" },
    { offset:  180, value: "Baghdad", text: "(UTC+03:00) Baghdad" },
    { offset:  180, value: "Kaliningrad, Minsk", text: "(UTC+03:00) Kaliningrad, Minsk" },
    { offset:  180, value: "Kuwait, Riyadh", text: "(UTC+03:00) Kuwait, Riyadh" },
    { offset:  180, value: "Nairobi", text: "(UTC+03:00) Nairobi" },
    { offset:  210, value: "Tehran", text: "(UTC+03:30) Tehran" },
    { offset:  240, value: "Abu Dhabi, Muscat", text: "(UTC+04:00) Abu Dhabi, Muscat" },
    { offset:  240, value: "Baku", text: "(UTC+04:00) Baku" },
    { offset:  240, value: "Moscow, St. Petersburg, Volgograd", text: "(UTC+04:00) Moscow, St. Petersburg, Volgograd" },
    { offset:  240, value: "Port Louis", text: "(UTC+04:00) Port Louis" },
    { offset:  240, value: "Tbilisi", text: "(UTC+04:00) Tbilisi" },
    { offset:  240, value: "Yerevan", text: "(UTC+04:00) Yerevan" },
    { offset:  270, value: "Kabul", text: "(UTC+04:30) Kabul" },
    { offset:  300, value: "Islamabad, Karachi", text: "(UTC+05:00) Islamabad, Karachi" },
    { offset:  300, value: "Tashkent", text: "(UTC+05:00) Tashkent" },
    { offset:  330, value: "Chennai, Kolkata, Mumbai, New Delhi", text: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
    { offset:  330, value: "Sri Jayawardenepura", text: "(UTC+05:30) Sri Jayawardenepura" },
    { offset:  345, value: "Kathmandu", text: "(UTC+05:45) Kathmandu" },
    { offset:  360, value: "Astana", text: "(UTC+06:00) Astana" },
    { offset:  360, value: "Dhaka", text: "(UTC+06:00) Dhaka" },
    { offset:  360, value: "Ekaterinburg", text: "(UTC+06:00) Ekaterinburg" },
    { offset:  390, value: "Yangon (Rangoon)", text: "(UTC+06:30) Yangon (Rangoon)" },
    { offset:  420, value: "Bangkok, Hanoi, Jakarta", text: "(UTC+07:00) Bangkok, Hanoi, Jakarta" },
    { offset:  420, value: "Novosibirsk", text: "(UTC+07:00) Novosibirsk" },
    { offset:  480, value: "Beijing, Chongqing, Hong Kong, Urumqi", text: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
    { offset:  480, value: "Krasnoyarsk", text: "(UTC+08:00) Krasnoyarsk" },
    { offset:  480, value: "Kuala Lumpur, Singapore", text: "(UTC+08:00) Kuala Lumpur, Singapore" },
    { offset:  480, value: "Perth", text: "(UTC+08:00) Perth" },
    { offset:  480, value: "Taipei", text: "(UTC+08:00) Taipei" },
    { offset:  480, value: "Ulaanbaatar", text: "(UTC+08:00) Ulaanbaatar" },
    { offset:  540, value: "Irkutsk", text: "(UTC+09:00) Irkutsk" },
    { offset:  540, value: "Osaka, Sapporo, Tokyo", text: "(UTC+09:00) Osaka, Sapporo, Tokyo" },
    { offset:  540, value: "Seoul", text: "(UTC+09:00) Seoul" },
    { offset:  570, value: "Adelaide", text: "(UTC+09:30) Adelaide" },
    { offset:  570, value: "Darwin", text: "(UTC+09:30) Darwin" },
    { offset:  600, value: "Brisbane", text: "(UTC+10:00) Brisbane" },
    { offset:  600, value: "Canberra, Melbourne, Sydney", text: "(UTC+10:00) Canberra, Melbourne, Sydney" },
    { offset:  600, value: "Guam, Port Moresby", text: "(UTC+10:00) Guam, Port Moresby" },
    { offset:  600, value: "Hobart", text: "(UTC+10:00) Hobart" },
    { offset:  600, value: "Yakutsk", text: "(UTC+10:00) Yakutsk" },
    { offset:  660, value: "Solomon Is., New Caledonia", text: "(UTC+11:00) Solomon Is., New Caledonia" },
    { offset:  660, value: "Vladivostok", text: "(UTC+11:00) Vladivostok" },
    { offset:  720, value: "Auckland, Wellington", text: "(UTC+12:00) Auckland, Wellington" },
    { offset:  720, value: "Coordinated Universal Time+12", text: "(UTC+12:00) Coordinated Universal Time+12" },
    { offset:  720, value: "Fiji", text: "(UTC+12:00) Fiji" },
    { offset:  720, value: "Magadan", text: "(UTC+12:00) Magadan" },
    { offset:  780, value: "Nuku'alofa", text: "(UTC+13:00) Nuku'alofa" },
    { offset:  780, value: "Samoa", text: "(UTC+13:00) Samoa" }
];

module.exports = gv_timeZoneData;